package cz.roman.spanek.courses.hibernate.model;
// Generated 24.4.2018 9:20:27 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Kontakt generated by hbm2java
 */
@Entity
@Table(name = "kontakt", schema = "public")
public class Kontakt implements java.io.Serializable {

	private String cislo;
	private Firma firma;

	public Kontakt() {
	}

	public Kontakt(String cislo, Firma firma) {
		this.cislo = cislo;
		this.firma = firma;
	}

	@Id

	@Column(name = "cislo", unique = true, nullable = false, length = 50)
	public String getCislo() {
		return this.cislo;
	}

	public void setCislo(String cislo) {
		this.cislo = cislo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ico", nullable = false)
	public Firma getFirma() {
		return this.firma;
	}

	public void setFirma(Firma firma) {
		this.firma = firma;
	}

}
