package cz.roman.spanek.courses.hibernate.model;
// Generated 24.4.2018 9:20:27 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Omezeni generated by hbm2java
 */
@Entity
@Table(name = "omezeni", schema = "public")
@SequenceGenerator(name = "omezeni_id_omezeni_seq", sequenceName = "omezeni_id_omezeni_seq", initialValue = 1, allocationSize = 1)
public class Omezeni implements java.io.Serializable {

	private int idOmezeni;
	private Silnice silnice;
	private int kmOmzeni;
	private int prujezdnost;
	private Date odstranitDo;
	private String omezeniTyp;
	private Date odtranenoDatum;
	private Set<Firma> firmas = new HashSet<Firma>(0);

	public Omezeni() {
	}

	public Omezeni(int idOmezeni, Silnice silnice, int kmOmzeni, int prujezdnost, Date odstranitDo, String omezeniTyp) {
		this.idOmezeni = idOmezeni;
		this.silnice = silnice;
		this.kmOmzeni = kmOmzeni;
		this.prujezdnost = prujezdnost;
		this.odstranitDo = odstranitDo;
		this.omezeniTyp = omezeniTyp;
	}

	public Omezeni(int idOmezeni, Silnice silnice, int kmOmzeni, int prujezdnost, Date odstranitDo, String omezeniTyp,
			Date odtranenoDatum, Set<Firma> firmas) {
		this.idOmezeni = idOmezeni;
		this.silnice = silnice;
		this.kmOmzeni = kmOmzeni;
		this.prujezdnost = prujezdnost;
		this.odstranitDo = odstranitDo;
		this.omezeniTyp = omezeniTyp;
		this.odtranenoDatum = odtranenoDatum;
		this.firmas = firmas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "omezeni_id_omezeni_seq")
	@Column(name = "id_omezeni", unique = true, nullable = false)
	public int getIdOmezeni() {
		return this.idOmezeni;
	}

	public void setIdOmezeni(int idOmezeni) {
		this.idOmezeni = idOmezeni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cislo_silnice", nullable = false)
	public Silnice getSilnice() {
		return this.silnice;
	}

	public void setSilnice(Silnice silnice) {
		this.silnice = silnice;
	}

	@Column(name = "km_omzeni", nullable = false)
	public int getKmOmzeni() {
		return this.kmOmzeni;
	}

	public void setKmOmzeni(int kmOmzeni) {
		this.kmOmzeni = kmOmzeni;
	}

	@Column(name = "prujezdnost", nullable = false)
	public int getPrujezdnost() {
		return this.prujezdnost;
	}

	public void setPrujezdnost(int prujezdnost) {
		this.prujezdnost = prujezdnost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "odstranit_do", nullable = false, length = 29)
	public Date getOdstranitDo() {
		return this.odstranitDo;
	}

	public void setOdstranitDo(Date odstranitDo) {
		this.odstranitDo = odstranitDo;
	}

	@Column(name = "omezeni_typ", nullable = false, length = 150)
	public String getOmezeniTyp() {
		return this.omezeniTyp;
	}

	public void setOmezeniTyp(String omezeniTyp) {
		this.omezeniTyp = omezeniTyp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "odtraneno_datum", length = 29)
	public Date getOdtranenoDatum() {
		return this.odtranenoDatum;
	}

	public void setOdtranenoDatum(Date odtranenoDatum) {
		this.odtranenoDatum = odtranenoDatum;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "omezeni_firma", schema = "public", joinColumns = {
			@JoinColumn(name = "id_omezeni", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ico", nullable = false, updatable = false) })
	public Set<Firma> getFirmas() {
		return this.firmas;
	}

	public void setFirmas(Set<Firma> firmas) {
		this.firmas = firmas;
	}

}
