package cz.roman.spanek.courses.hibernate.model;
// Generated 24.4.2018 9:20:27 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Silnice generated by hbm2java
 */
@Entity
@Table(name = "silnice", schema = "public")
public class Silnice implements java.io.Serializable {

	private String cisloSilnice;
	private String trida;
	private int kmCelkem;
	private Set<Omezeni> omezenis = new HashSet<Omezeni>(0);

	public Silnice() {
	}

	public Silnice(String cisloSilnice, String trida, int kmCelkem) {
		this.cisloSilnice = cisloSilnice;
		this.trida = trida;
		this.kmCelkem = kmCelkem;
	}

	public Silnice(String cisloSilnice, String trida, int kmCelkem, Set<Omezeni> omezenis) {
		this.cisloSilnice = cisloSilnice;
		this.trida = trida;
		this.kmCelkem = kmCelkem;
		this.omezenis = omezenis;
	}

	@Id

	@Column(name = "cislo_silnice", unique = true, nullable = false, length = 15)
	public String getCisloSilnice() {
		return this.cisloSilnice;
	}

	public void setCisloSilnice(String cisloSilnice) {
		this.cisloSilnice = cisloSilnice;
	}

	@Column(name = "trida", nullable = false, length = 150)
	public String getTrida() {
		return this.trida;
	}

	public void setTrida(String trida) {
		this.trida = trida;
	}

	@Column(name = "km_celkem", nullable = false)
	public int getKmCelkem() {
		return this.kmCelkem;
	}

	public void setKmCelkem(int kmCelkem) {
		this.kmCelkem = kmCelkem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "silnice")
	public Set<Omezeni> getOmezenis() {
		return this.omezenis;
	}

	public void setOmezenis(Set<Omezeni> omezenis) {
		this.omezenis = omezenis;
	}

}
